version: '3'

services:
  database:
    container_name: database
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5555:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
