jms_serializer:
    # https://stackoverflow.com/questions/40754147/symfony-fosrestbundle-enablemaxdepthchecks-default-to-true
    # for some unknown reason, @View(serializerEnableMaxDepthChecks=true) annotation does not work.. :(
    default_context:
        serialization:
            enable_max_depth_checks: true
    property_naming:
        id: jms_serializer.identical_property_naming_strategy
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
